services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    # ports:
    #   - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/todolist?schema=public
    depends_on:
      - db
    volumes:
      - ./server/prisma:/app/prisma
    secrets:
      - db_url
      - jwt_secret
      - admin_secret

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todolist
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    # ports:
    #   - "80:80"
    depends_on:
      - server

secrets:
  db_url:
    file: ./secrets/db_url.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt
  admin_secret:
    file: ./secrets/admin_secret.txt

volumes:
  postgres_data:
